# Generated by Django 5.0.7 on 2026-06-21 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone')),
                ('request', models.TextField(blank=True, verbose_name='Request')),
                ('customer_type', models.CharField(choices=[('standard', 'Standard'), ('special', 'Special')], default='standard', max_length=20, verbose_name='Customer Type')),
                ('current_stage', models.CharField(choices=[('phone_call', 'Phone Call'), ('personal_interview', 'Personal Interview'), ('location_visit', 'Location Visit'), ('contract_signed', 'Contract Signed')], default='phone_call', max_length=30, verbose_name='Current Stage')),
                ('stage_start_date', models.DateTimeField(auto_now_add=True, verbose_name='Stage Start Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Sales Rep')),
            ],
            options={
                'verbose_name': 'Customer',
                'ordering': ['-created_at'],
                'unique_together': {('sales_rep', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='CustomerStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stage', models.CharField(choices=[('phone_call', 'Phone Call'), ('personal_interview', 'Personal Interview'), ('location_visit', 'Location Visit'), ('contract_signed', 'Contract Signed')], max_length=30)),
                ('new_stage', models.CharField(choices=[('phone_call', 'Phone Call'), ('personal_interview', 'Personal Interview'), ('location_visit', 'Location Visit'), ('contract_signed', 'Contract Signed')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='webapp.customer')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('customers_acquired', models.IntegerField(default=0)),
                ('contracts_signed', models.IntegerField(default=0)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('sales_rep', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('edit', 'Edit'), ('reset_password', 'Reset Password'), ('delete', 'Delete')], max_length=20)),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('granted_to', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='SalesTeamMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('sales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_mapping', to=settings.AUTH_USER_MODEL)),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('team_number', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('team_leader', 'Team Leader'), ('sales', 'Sales')], default='sales', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
