# Generated by Django 5.0.7 on 2026-05-15 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_record_tall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='category',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('request', models.TextField(blank=True, help_text="Customer's needs/requirements")),
                ('current_stage', models.CharField(choices=[('phone_call', 'Phone Call'), ('personal_interview', 'Personal Interview'), ('location_visit', 'Location Visit'), ('contract_signed', 'Contract Signed')], default='phone_call', max_length=30)),
                ('stage_start_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sales_rep', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='CustomerStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stage', models.CharField(choices=[('phone_call', 'Phone Call'), ('personal_interview', 'Personal Interview'), ('location_visit', 'Location Visit'), ('contract_signed', 'Contract Signed')], max_length=30)),
                ('new_stage', models.CharField(choices=[('phone_call', 'Phone Call'), ('personal_interview', 'Personal Interview'), ('location_visit', 'Location Visit'), ('contract_signed', 'Contract Signed')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='webapp.customer')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('customers_acquired', models.IntegerField(default=0)),
                ('contracts_signed', models.IntegerField(default=0)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('sales_rep', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('delete_member', 'Can Delete Members'), ('edit_client', 'Can Edit Other Sales Clients'), ('view_reports', 'Can View Reports'), ('manage_team', 'Can Manage Team')], max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_given', to=settings.AUTH_USER_MODEL)),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('granted_to', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='SalesTeamMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('sales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_mapping', to=settings.AUTH_USER_MODEL)),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('team_leader', 'Team Leader'), ('sales', 'Sales')], default='sales', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
