# Generated by Django 5.0.7 on 2026-05-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_record_category_customer_customerstagehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
