# Generated by Django 5.0.7 on 2026-05-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_userrole_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
