# Generated by Django on 2026-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_userrole_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='team_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
