# Generated by Django 5.0.7 on 2026-05-17 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_add_userrole_team_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer'},
        ),
        migrations.RemoveField(
            model_name='permissiongrant',
            name='granted_at',
        ),
        migrations.RemoveField(
            model_name='permissiongrant',
            name='granted_by',
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_stage',
            field=models.CharField(choices=[('phone_call', 'Phone Call'), ('personal_interview', 'Personal Interview'), ('location_visit', 'Location Visit'), ('contract_signed', 'Contract Signed')], default='phone_call', max_length=30, verbose_name='Current Stage'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='request',
            field=models.TextField(blank=True, verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Sales Rep'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stage_start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Stage Start Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='permissiongrant',
            name='permission',
            field=models.CharField(choices=[('edit', 'Edit'), ('reset_password', 'Reset Password'), ('delete', 'Delete')], max_length=20),
        ),
    ]
