# Generated by Django 5.0.7 on 2026-06-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('special', 'Special')], default='standard', max_length=20, verbose_name='Customer Type'),
        ),
    ]
